baseURL = "https://www.robhorrigan.com/"
languageCode = "en-us"
title = "Rob Horrigan | Full-Stack Developer"
theme = "hugo-lodi-theme"
googleAnalytics = "UA-89428345-1"
publishDir = "docs"
disableKinds=["RSS","404","taxonomy","taxonomyTerm"]

[params]
    theme_color = "#3A7CA5"
    description = "Portfolio of Rob Horrigan | Full-Stack Developer and Technologist from Austin, TX"
    description_photo = "portfolio.jpg"
    favicon = "favicon.png"
    logo = "logo.png"
    email = "roberthorrigan@gmail.com"
    twitter = "rob_horrigan"
    linkedin = "//www.linkedin.com/in/roberthorrigan"
    medium = "rob_horrigan"
    github = "robhorrigan"

[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "avatar.jpg"
    subtitle = "Hi! I'm Rob, a Full-Stack Developer and Technologist from Austin, TX."
    hero_right = ["**Currently a Tech Lead at [The Knot Worldwide](https://www.theknotww.com/) in Austin. Previously doing rapid MVP prototyping for startups in New York City.**", "My passion is using technology to help people solve problems. I enjoy working through the entire product lifecycle, from ideation to launch.", "I have a background in software engineering, primarily as a full-stack developer building web experiences using the latest technologies.",  "I'm always on the look-out for the latest technology trends and enjoy connecting with others.", "Feel free to [reach out](https://www.linkedin.com/in/roberthorrigan/) with opportunities."]
    resume = "ResumeHorrigan.pdf"

# [params.process]
#     enable = true
#     title = "My Process"
#     subtitle = "Full Process Design"

# [params.case_studies]
#     enable = true
#     title = "Case Studies"
#     subtitle = "Selected Works"

[params.footer]
    enable = false
